name: thcMobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^1.0.8
#  agora_rtc_engine: ^3.3.2
  # agora_rtc_engine: ^3.1.3
  cached_network_image: ^2.3.2+1
  cloud_firestore: ^0.14.0+2
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  permission_handler: ^5.0.1+1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_messaging: ^7.0.3
  firebase_storage: ^4.0.0
  firebase_analytics: ^5.0.2
  flutter_calendar: ^0.0.1
  flutter_rating_bar: ^3.0.1+1
#  flutter_twilio_voice: ^0.0.4
  fluttertoast: ^7.0.2
  google_maps_flutter: ^0.5.28+1
  google_sign_in: ^4.5.6
  http: ^0.12.1
  image_picker: ^0.6.7+15
  loading_overlay: ^0.2.1
  page_transition: ^1.1.5
  # file_picker: ^2.0.0
#  adaptive_dialog: ^0.9.2
  path: ^1.6.2
#  path_provider: ^1.6.5
  hive: ^1.4.1+1
  # permission_handler: ^4.4.0+hotfix.2
  # permission_handler: ^5.0.1+1 
  provider: ^4.1.2
  shared_preferences: ">=0.5.7+3 <2.0.0"
  table_calendar: ^2.3.0
#  timeago: ^2.0.27
#  uuid: ^2.2.2
  flutter_paystack: ^1.0.4+1
#  sms_autofill: ^1.2.6
  flutter_local_notifications: 1.4.4+4 #1.4.0
  photo_view: ^0.10.2 #0.5.0
  intl: ^0.16.1
#  device_calendar: ^3.1.0
  mask_text_input_formatter: ^1.2.1
  flutter_webrtc: ^0.2.8
  share: ^0.6.5+4



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/SofiaPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SofiaPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SofiaPro-Regular.ttf
        - asset: assets/fonts/SofiaPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SofiaPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SofiaPro-BoldItalic.ttf
          weight: 700
          style: italic
